name: ntu-nlp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.0.1
  - blas=1.0
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - cymem=2.0.2
  - cytoolz=0.9.0.1
  - dill=0.2.9
  - idna=2.8
  - intel-openmp=2019.4
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libopenblas=0.3.6
  - libstdcxx-ng=9.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - msgpack-numpy=0.4.3.2
  - msgpack-python=0.6.1
  - murmurhash=1.0.2
  - ncurses=6.1
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.1.1d
  - pandas=0.25.1
  - pip=19.2.3
  - plac=0.9.6
  - preshed=2.0.1
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.7.1
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyyaml=5.1.2
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.4.0
  - six=1.12.0
  - spacy=2.0.16
  - sqlite=3.30.0
  - thinc=6.12.1
  - tk=8.6.8
  - toolz=0.10.0
  - tqdm=4.36.1
  - ujson=1.35
  - urllib3=1.24.2
  - wheel=0.33.6
  - wrapt=1.10.11
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - regex==2018.1.10
    - allennlp==0.9.0
    - pandas==0.24.2
    - spacy==2.1.4
    - nltk==3.2.4
    - sklearn==0.21.3
prefix: /home/lym/anaconda3/envs/ntu-nlp

